# Generated by Django 4.0.4 on 2022-06-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_slug', models.SlugField(max_length=25)),
                ('url', models.URLField()),
                ('server_ip', models.CharField(default='127.0.0.1', max_length=100)),
                ('version', models.CharField(max_length=25)),
                ('branch', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failure', 'Failure'), ('Building', 'Building'), ('Waiting', 'Waiting'), ('Paused', 'Paused'), ('Unknown', 'Unknown')], default='Unknown', max_length=25)),
                ('note', models.CharField(max_length=100, null=True)),
                ('started', models.DateTimeField()),
                ('ended', models.DateTimeField()),
                ('duration', models.DurationField(null=True)),
            ],
            options={
                'ordering': ['-started'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('git_url', models.URLField()),
                ('server_ip', models.CharField(default='127.0.0.1', max_length=100)),
                ('project_slug', models.SlugField(max_length=25, unique=True)),
                ('svg_path', models.TextField(choices=[('<path d="M2 16.1A5 5 0 0 1 5.9 20M2 12.05A9 9 0 0 1 9.95 20M2 8V6a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2h-6"></path><line x1="2" y1="20" x2="2.01" y2="20"></line>', 'Roboguide'), ('<rect x="5" y="2" width="14" height="20" rx="2" ry="2"></rect><line x1="12" y1="18" x2="12.01" y2="18"></line>', 'Servers'), ('<rect x="2" y="3" width="20" height="14" rx="2" ry="2"></rect><line x1="8" y1="21" x2="16" y2="21"></line><line x1="12" y1="17" x2="12" y2="21"></line>', 'Pc'), ('<rect x="4" y="4" width="16" height="16" rx="2" ry="2"></rect><rect x="9" y="9" width="6" height="6"></rect><line x1="9" y1="1" x2="9" y2="4"></line><line x1="15" y1="1" x2="15" y2="4"></line><line x1="9" y1="20" x2="9" y2="23"></line><line x1="15" y1="20" x2="15" y2="23"></line><line x1="20" y1="9" x2="23" y2="9"></line><line x1="20" y1="14" x2="23" y2="14"></line><line x1="1" y1="9" x2="4" y2="9"></line><line x1="1" y1="14" x2="4" y2="14"></line>', 'Miroservice')], default='<rect x="5" y="2" width="14" height="20" rx="2" ry="2"></rect><line x1="12" y1="18" x2="12.01" y2="18"></line>')),
                ('version', models.CharField(max_length=25)),
                ('branch', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failure', 'Failure'), ('Building', 'Building'), ('Waiting', 'Waiting'), ('Paused', 'Paused'), ('Unknown', 'Unknown')], default='Unknown', max_length=25)),
                ('note', models.CharField(max_length=100, null=True)),
                ('started', models.DateTimeField()),
                ('ended', models.DateTimeField()),
                ('duration', models.DurationField(null=True)),
            ],
            options={
                'ordering': ['-started'],
            },
        ),
    ]
