# Generated by Django 4.2 on 2023-04-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_alter_provider_id_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='sex',
            field=models.CharField(max_length=30),
        ),
    ]
